### ISSUE TITLE
Outdated Nlog dependency

### ISSUE THREAD

**Issue by frogger3d** [ninject/Ninject.Extensions.Logging#25]
Any chance nlog version 3 will be supported? Is the main problem that support for several old .Net frameworks has been dropped?

https://github.com/NLog/NLog/releases/tag/v3.0

**Comment by estiller** [comment]
I implemented an NLog3 extension and requested the project authors to pull the changes in.
https://github.com/ninject/Ninject.Extensions.Logging/pull/26
I hope it will be incorporated soon.
