### ISSUE TITLE
Release of NLog3 extension package

### ISSUE THREAD

**Issue by estiller** [ninject/Ninject.Extensions.Logging#28]
Hi,
Is there an estimate as to when a new stable version of the NLog3 extension packages would be released?
Alternatively, is it possible to release only a version of Ninject.Extensions.Logging.nlog3 package as a stable version numbered 3.2.1 (last stable version)?
The reason I am asking is that I would like to release a package which takes dependency upon this new extension, and I cannot mark my package as stable as long as the NLog3 extension is marked as prerelease.

I truly appreciate your efforts as this is a great project and great extension.

Regards,
Eran

**Comment by scott-xu** [comment]
3.2.2 released
