### ISSUE TITLE
Release of NLog4 extension package

### ISSUE THREAD

**Issue by estiller** [ninject/Ninject.Extensions.Logging#31]
Hi,
For the same reason specified in https://github.com/ninject/Ninject.Extensions.Logging/issues/28, is there an estimated timeframe for the release of a "Release" NuGet package for the NLog4 extension?

Again, I truly appreciate your efforts.

Regards,
Eran

**Comment by scott-xu** [comment]
You can use the CI build. https://www.nuget.org/packages/Ninject.Extensions.Logging.nlog4

**Comment by estiller** [comment]
Yes, I already saw that. My problem is that the package is marked as Pre-Release, and as a result if I create a package which takes a dependency on this package I MUST mark it as pre-release as well.
When can we expect a "Release" version of the package (specifically of the NLog4 extension)?

**Comment by scott-xu** [comment]
Will do it soon

**Comment by scott-xu** [comment]
Done
