### ISSUE TITLE
Update or New Serilog implementation

### ISSUE THREAD

**Issue by dbroudy** [ninject/Ninject.Extensions.Logging#37]
The current version used for Serilog is over 2 years old. Some extensions (Serilog.Sinks.MSSqlServer in my case) require >= 2.0.

Would you consider a pull request to either update the version of the current or to create a Serilog2 package that supports >= 2.0 (and >= .net45)?

**Comment by CarlosRamirezRamos** [comment]
it will be nice to update to serilog2

**Comment by scott-xu** [comment]
done
