### ISSUE TITLE
Compatibility with Ninject 3.3.0

### ISSUE THREAD

**Issue by mivra** [ninject/Ninject.Extensions.Logging#38]
Currently on nuget.org (https://www.nuget.org/packages/Ninject.Extensions.Logging/3.2.3) the dependency 
for Ninject library requires version < 3.3.0 . Version 3.3.0 was released in September and version 3.3.1 today. would it be possible to release a new nuget package?

**Comment by scott-xu** [comment]
Ninject.Extensions.Logging 3.3.0 beta1 released just now.
